/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * E-Commerce Store API
 * OpenAPI spec version: 0.2.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all products
 */
export const ListProductsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  section: zod.coerce.string().optional(),
  isHotSelling: zod.coerce.boolean().optional(),
  isNewArrival: zod.coerce.boolean().optional(),
  isOfferProduct: zod.coerce.boolean().optional(),
  limit: zod.coerce.number().optional(),
  search: zod.coerce.string().optional(),
});

export const ListProductsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  originalPrice: zod.number().nullish(),
  discountPrice: zod.number().nullish(),
  imageUrl: zod.string(),
  images: zod.array(zod.string()),
  category: zod.string(),
  section: zod.string(),
  colors: zod.array(zod.string()),
  stock: zod.number(),
  isHotSelling: zod.boolean(),
  isNewArrival: zod.boolean(),
  isOfferProduct: zod.boolean(),
  inStock: zod.boolean(),
  createdAt: zod.string(),
});
export const ListProductsResponse = zod.array(ListProductsResponseItem);

/**
 * @summary Create a product (admin)
 */
export const CreateProductBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  originalPrice: zod.number().nullish(),
  discountPrice: zod.number().nullish(),
  imageUrl: zod.string(),
  images: zod.array(zod.string()),
  category: zod.string(),
  section: zod.string(),
  colors: zod.array(zod.string()).optional(),
  stock: zod.number().optional(),
  isHotSelling: zod.boolean().optional(),
  isNewArrival: zod.boolean().optional(),
  isOfferProduct: zod.boolean().optional(),
  inStock: zod.boolean(),
});

/**
 * @summary Get a single product
 */
export const GetProductParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  originalPrice: zod.number().nullish(),
  discountPrice: zod.number().nullish(),
  imageUrl: zod.string(),
  images: zod.array(zod.string()),
  category: zod.string(),
  section: zod.string(),
  colors: zod.array(zod.string()),
  stock: zod.number(),
  isHotSelling: zod.boolean(),
  isNewArrival: zod.boolean(),
  isOfferProduct: zod.boolean(),
  inStock: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Update a product (admin)
 */
export const UpdateProductParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProductBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  originalPrice: zod.number().nullish(),
  discountPrice: zod.number().nullish(),
  imageUrl: zod.string(),
  images: zod.array(zod.string()),
  category: zod.string(),
  section: zod.string(),
  colors: zod.array(zod.string()).optional(),
  stock: zod.number().optional(),
  isHotSelling: zod.boolean().optional(),
  isNewArrival: zod.boolean().optional(),
  isOfferProduct: zod.boolean().optional(),
  inStock: zod.boolean(),
});

export const UpdateProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  originalPrice: zod.number().nullish(),
  discountPrice: zod.number().nullish(),
  imageUrl: zod.string(),
  images: zod.array(zod.string()),
  category: zod.string(),
  section: zod.string(),
  colors: zod.array(zod.string()),
  stock: zod.number(),
  isHotSelling: zod.boolean(),
  isNewArrival: zod.boolean(),
  isOfferProduct: zod.boolean(),
  inStock: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Delete a product (admin)
 */
export const DeleteProductParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteProductResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary List all categories
 */
export const ListCategoriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  imageUrl: zod.string(),
});
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem);

/**
 * @summary Create a category (admin)
 */
export const CreateCategoryBody = zod.object({
  name: zod.string(),
  imageUrl: zod.string(),
});

/**
 * @summary Delete a category (admin)
 */
export const DeleteCategoryParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteCategoryResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary List all banners
 */
export const ListBannersResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  subtitle: zod.string().nullish(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullish(),
  buttonText: zod.string().nullish(),
  sortOrder: zod.number(),
  isActive: zod.boolean(),
});
export const ListBannersResponse = zod.array(ListBannersResponseItem);

/**
 * @summary Create a banner (admin)
 */
export const CreateBannerBody = zod.object({
  title: zod.string(),
  subtitle: zod.string().nullish(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullish(),
  buttonText: zod.string().nullish(),
  sortOrder: zod.number(),
  isActive: zod.boolean(),
});

/**
 * @summary Update a banner (admin)
 */
export const UpdateBannerParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBannerBody = zod.object({
  title: zod.string(),
  subtitle: zod.string().nullish(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullish(),
  buttonText: zod.string().nullish(),
  sortOrder: zod.number(),
  isActive: zod.boolean(),
});

export const UpdateBannerResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  subtitle: zod.string().nullish(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullish(),
  buttonText: zod.string().nullish(),
  sortOrder: zod.number(),
  isActive: zod.boolean(),
});

/**
 * @summary Delete a banner (admin)
 */
export const DeleteBannerParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteBannerResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary List all orders (admin)
 */
export const ListOrdersResponseItem = zod.object({
  id: zod.number(),
  orderId: zod.string(),
  customerName: zod.string(),
  customerEmail: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      imageUrl: zod.string(),
    }),
  ),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "shipping",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListOrdersResponse = zod.array(ListOrdersResponseItem);

/**
 * @summary Place an order
 */
export const CreateOrderBody = zod.object({
  customerName: zod.string(),
  customerEmail: zod.string().optional().default(""),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.union([zod.string(), zod.number()]).transform(String),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      imageUrl: zod.string().optional().default(""),
      color: zod.string().optional().default(""),
    }),
  ),
  total: zod.number(),
  paymentMethod: zod.enum(["cod", "online"]),
  notes: zod.string().nullish(),
});

/**
 * @summary Get a single order
 */
export const GetOrderParams = zod.object({
  id: zod.coerce.number(),
});

export const GetOrderResponse = zod.object({
  id: zod.number(),
  orderId: zod.string(),
  customerName: zod.string(),
  customerEmail: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      imageUrl: zod.string(),
    }),
  ),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "shipping",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Update order status (admin)
 */
export const UpdateOrderStatusParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateOrderStatusBody = zod.object({
  status: zod.enum([
    "pending",
    "confirmed",
    "shipping",
    "delivered",
    "cancelled",
  ]),
});

export const UpdateOrderStatusResponse = zod.object({
  id: zod.number(),
  orderId: zod.string(),
  customerName: zod.string(),
  customerEmail: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      imageUrl: zod.string(),
    }),
  ),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "shipping",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Delete an order (admin)
 */
export const DeleteOrderParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteOrderResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Send email verification code
 */
export const SendVerificationCodeBody = zod.object({
  email: zod.string(),
});

export const SendVerificationCodeResponse = zod.object({
  message: zod.string(),
  devCode: zod.string().nullish(),
});

/**
 * @summary Verify code and login
 */
export const VerifyCodeBody = zod.object({
  email: zod.string(),
  code: zod.string(),
});

export const VerifyCodeResponse = zod.object({
  token: zod.string(),
  user: zod.object({
    id: zod.number(),
    name: zod.string(),
    email: zod.string(),
    isAdmin: zod.boolean(),
    createdAt: zod.string(),
  }),
});

/**
 * @summary Admin login with password
 */
export const LoginAdminBody = zod.object({
  email: zod.string(),
  password: zod.string(),
});

export const LoginAdminResponse = zod.object({
  token: zod.string(),
  admin: zod.object({
    id: zod.number(),
    email: zod.string(),
  }),
});

/**
 * @summary List all users (admin)
 */
export const ListUsersResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  isAdmin: zod.boolean(),
  createdAt: zod.string(),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);

/**
 * @summary Update user role (admin)
 */
export const UpdateUserRoleParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateUserRoleBody = zod.object({
  isAdmin: zod.boolean(),
});

export const UpdateUserRoleResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  isAdmin: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Get current user's orders
 */
export const GetUserOrdersResponseItem = zod.object({
  id: zod.number(),
  orderId: zod.string(),
  customerName: zod.string(),
  customerEmail: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.number(),
      quantity: zod.number(),
      imageUrl: zod.string(),
    }),
  ),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "shipping",
    "delivered",
    "cancelled",
  ]),
  paymentMethod: zod.enum(["cod", "online"]),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});
export const GetUserOrdersResponse = zod.array(GetUserOrdersResponseItem);